### ISSUE TITLE
Could you explain how the csv file / input file is supposed to be

### ISSUE THREAD

**Issue by nupur0294** [ZoharKapach/570Project#1]
Could you explain how the csv file / input file is supposed to be

**Comment by ZoharKapach** [comment]
Sorry for the slow reply. This work is a modification of this implementation:
https://github.com/javiribera/locating-objects-without-bboxes

I will add an example csv to this file very soon.

**Comment by ZoharKapach** [comment]
So i actually already had an example. You can find the csv file here: 
https://github.com/ZoharKapach/570Project/tree/master/locating-objects-classes/mpii_human_pose_v1/images
